const Router = require('express')
const router = new Router()
const deviceController = require('../controllers/deviceController')
const checkRole = require('../middleware/checkRoleMiddleware')
const authMiddleware = require('../middleware/authMiddleware')
router.post('/', checkRole('ADMIN'),deviceController.create)
router.get('/', deviceController.getAll)
router.get('/:id', deviceController.getOne)
router.post('/basket',authMiddleware, deviceController.setBasket)
router.get('/basket/:id', authMiddleware, deviceController.getBasket)
module.exports = router